# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  # - name: Posts
  #   url: '#posts'
  #   weight: 20
  - name: Projects
    url: 'project'
    weight: 20
  - name: Publications
    url: 'publication'
    weight: 30
  - name: Teaching
    url: 'teaching'
    weight: 40
  - name: Events
    url: 'events'
    weight: 50
  - name: Videos
    url: 'videos'
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 70
  - name: CV
    url: uploads/Large_CV.pdf
    weight: 80
